name: "Task 2: Ansible Components"

on:
  push:
    paths:
      - 'task2/**' # Запускається, коли змінюю файли в папці task2

jobs:
  ansible:
    name: "Налаштування цільового вузла" # Замість цифр пишу текст, щоб назва була універсальною
    runs-on: ubuntu-latest
    steps:
      - name: "Копіюю код мого репозиторію"
        uses: actions/checkout@v4

      - name: "Налаштовую SSH ключ для доступу до сервака"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: "Перевірка синтаксису плейбука"
        # Перевіряю, чи все ок з кодом перед тим як реально щось ставити
        run: ansible-playbook -i task2/hosts.ini task2/playbook.yml --syntax-check

      - name: "Запуск встановлення компонентів"
        # Ставлю Docker, Minikube та Helm на сервер
        run: |
          ansible-playbook -i task2/hosts.ini task2/playbook.yml \
          -e "ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"