name: "Task 2 & 3: Ansible & K8s Deploy"


on:
  push:
    paths:
      - 'task2/**'
      - 'task3/**'

jobs:
  ansible:
    name: "Налаштування та Деплой"
    runs-on: ubuntu-latest
    steps:
      - name: "Забираю код"
        uses: actions/checkout@v4

      - name: "Налаштовую SSH ключ"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: "Перевірка синтаксису"
        run: ansible-playbook -i task2/hosts.ini task2/playbook.yml --syntax-check

      - name: "Запуск плейбука (Інсталяція + Деплой)"
        run: |
          ansible-playbook -i task2/hosts.ini task2/playbook.yml \
          -e "ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"